// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdbzeleujwvjymwydtlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkYnplbGV1and2anltd3lkdGxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTcwNzYsImV4cCI6MjA2MzkzMzA3Nn0.yD57bFhWXGUImcUESAZM2LIUgfVIc19xycKRY0Am4vE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);